version: "3.9"

services:
  proxy:
    image: nginx:alpine
    ports:
      - "${OUTPUT_PORT}:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:Z
    networks:
      - internal_net
  
  postgres:
    image: postgres:17
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data:Z
    networks:
      - internal_net

  minio:
    image: minio/minio:latest
    env_file: .env
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio-data:/data:Z
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - internal_net

  
  minio-init:
    image: minio/mc:latest
    env_file: .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c '
        until mc alias set myminio http://minio:9000 \
              "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}" >/dev/null 2>&1
        do
          echo "Waiting for MinIO…" && sleep 2
        done

        if mc ls myminio/"${MINIO_BUCKET}" >/dev/null 2>&1; then
          echo "Bucket \"${MINIO_BUCKET}\" already exists; skipping initialization"
        else
          mc mb myminio/"${MINIO_BUCKET}" \
             && echo "Bucket \"${MINIO_BUCKET}\" created"
        fi

        mc anonymous set download myminio/"${MINIO_BUCKET}" \
         && echo "Bucket policy set to public‑read"
      '
  web:
    image: nginx:alpine
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:Z
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  minio-data:
  postgres-data:
