version: "3.9"

services:
  proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"                # venku dostupné jen proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:Z
    networks:
      - internal_net

  web:
    image: nginx:alpine
    container_name: webapp
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:Z
    expose:
      - "80"                 # pouze interně, nezveřejňujeme
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

