  version: "3.9"

  services:
    proxy:
      volumes:
        - ./proxy/prod.conf:/etc/nginx/conf.d/default.conf:ro,Z
    
    web:
      environment:
        FLASK_DEBUG: 0
        FLASK_ENV: production
        