version: "3.9"

services:
  proxy:
    volumes:
      - ./proxy/dev.conf:/etc/nginx/conf.d/default.conf:ro,Z

  postgres:
    ports:
      - "15432:5432"

  web:
    volumes:
      - ./web/src:/app/src:ro,Z